### ISSUE TITLE
Updating billing and shipping info

### ISSUE THREAD

**Issue by ChrisZieba** [lemonstand/lscloud-theme-coastal#14]
We've run into several serious bugs in the Costal theme:

1. It doesn't set the shipping country and state correctly (even before any scripts execute). It looks like the two address partials (checkout and profile) use the wrong variable for country/state ID when looping through the countries/states.

2. The billing/shipping address sync option is checked by default, so it overwrites the shipping address every time the page loads (even if they aren't supposed to be the same).

3. The billing/shipping address sync doesn't properly set the shipping country or state. It looks like the "updatePartials" event is triggered after syncing or updating the addresses, which re-populates the select elements with new options via Ajax that don't have anything selected. This turns US addresses into "Afganistan, Alabama", Canadian into "Afganistan, Alberta", etc.

**Comment by hotmeteor** [comment]
I think this has been resolved in #15.

**Comment by hotmeteor** [comment]
Resolved in https://github.com/lemonstand/lscloud-theme-coastal/commit/999e6413f996b974836f0efdf88c12010dfaea2d
