### ISSUE TITLE
Saving shipping address for profile always reverts back

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-coastal#15]
On /profile page, changing the shipping address and clicking saves makes it revert back to Afghanistan (or, the first country in the list, I assume).

**Comment by hotmeteor** [comment]
Is there a Lemonstand JS event that is triggered at the document level when an AJAX update completes?

**Comment by hotmeteor** [comment]
Never mind, found it looking in a different theme.

```
$(window).on('onAfterAjaxUpdate', function(){
    ...
});
```
