### ISSUE TITLE
When "shipping is the same" is checked, shipping should be disabled

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-coastal#16]
When the "my shipping information is the same is checked" you can still modify the shipping address. This creates some really weird behavior. When this is checked, the shipping fields should be disabled.

An example of this can be found in our latest themes with 1-page checkout.

![checkout_bill-ship-opt](https://cloud.githubusercontent.com/assets/1108337/7502125/8d5ab8dc-f3ee-11e4-986a-5fda6bf6d6d3.gif)

**Comment by hotmeteor** [comment]
Resolved in https://github.com/lemonstand/lscloud-theme-coastal/commit/999e6413f996b974836f0efdf88c12010dfaea2d
