### ISSUE TITLE
Is it possible to compile this theme?

### ISSUE THREAD

**Issue by brickcap** [lemonstand/lscloud-theme-coastal#28]
Hi,

I want to use the coastal theme in a project on my own. I was wondering if it's possible to use this template outside of lemonstand? In other words can I compile this theme using some mock data so that it can be showcased just like [this demo page](https://coastal.lemonstand.com/)? 

If so how can you let me know how? 

Thanks,
Akshat

**Comment by dhalarewich** [comment]
This is a LemonStand theme and as is will only work for LemonStand. We can't provide support on modifying it for other uses unfortunately.
