### ISSUE TITLE
Products can't be added to cart

### ISSUE THREAD

**Issue by aperdomo** [lemonstand/lscloud-theme-coastal#30]
# Steps to reproduce

1. Create a new store
2. Install Coastal
3. Add a product to cart

Looks like some changes may have regressed this functionality.

**Comment by tomcornall** [comment]
Looks like the default qty had spaces in the text input:

![coastal_ _faded_lemons](https://user-images.githubusercontent.com/14319209/30715871-ba746c1a-9ecc-11e7-966b-1d12395f55a0.png)
